#egyszerű értékek számolása a háromféle vállalat típusra: E10T49, E50T249 és E_GE250 külön-külön
get_NACE <- function(M0581_2Jegyen) {
  
  if (as.integer(M0581_2Jegyen) >= 1 & as.integer(M0581_2Jegyen) <= 3){
    return(paste("A", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 5 & as.integer(M0581_2Jegyen) <= 9){
    return(paste("B", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 10 & as.integer(M0581_2Jegyen) <= 33){
    return(paste("C", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 351 & as.integer(M0581_2Jegyen) <= 353){
    return(paste("D", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 36 & as.integer(M0581_2Jegyen) <= 39){
    return(paste("E", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 41 & as.integer(M0581_2Jegyen) <= 43){
    return(paste("F", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 45 & as.integer(M0581_2Jegyen) <= 47){
    return(paste("G", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 49 & as.integer(M0581_2Jegyen) <= 53){
    return(paste("H", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 55 & as.integer(M0581_2Jegyen) <= 56){
    return(paste("I", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 58 & as.integer(M0581_2Jegyen) <= 63){
    return(paste("J", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 64 & as.integer(M0581_2Jegyen) <= 66){
    return(paste("K", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) == 68){
    return("L")
  }
  
  if (as.integer(M0581_2Jegyen) >= 69 & as.integer(M0581_2Jegyen) <= 75){
    return(paste("M", M0581_2Jegyen, sep = ""))
  }
  
  if (as.integer(M0581_2Jegyen) >= 77 & as.integer(M0581_2Jegyen) <= 82){
    return(paste("N", M0581_2Jegyen, sep = ""))
  }
  
  return("Missing")
}


insert_Total <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & ACTIVITY == ACTIVITY_P & CIS_INDICATOR == CIS_INDICATOR_P) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_M71T73 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "M71" | ACTIVITY == "M72" | ACTIVITY == "M73")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_N <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "N77" | ACTIVITY == "N78" | ACTIVITY == "N79" | ACTIVITY == "N80" | ACTIVITY == "N81" | ACTIVITY == "N82")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_M <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "M69" | ACTIVITY == "M70" | ACTIVITY == "M71" | ACTIVITY == "M72" | ACTIVITY == "M73" | ACTIVITY == "M74" | ACTIVITY == "M75")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_J61T63 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "J61" | ACTIVITY == "J62" | ACTIVITY == "J63")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_J58T60 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "J58" | ACTIVITY == "J59" | ACTIVITY == "J60")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_K <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "K64" | ACTIVITY == "K65" | ACTIVITY == "K66")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_J <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "J58" | ACTIVITY == "J59" | ACTIVITY == "J60" | ACTIVITY == "J61" | ACTIVITY == "J62" | ACTIVITY == "J63")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_H52T53 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "H52" | ACTIVITY == "H53")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_H49T51 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "H49" | ACTIVITY == "H50" | ACTIVITY == "H51")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_H <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "H49" | ACTIVITY == "H50" | ACTIVITY == "H51" | ACTIVITY == "H52" | ACTIVITY == "H53")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_I <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "I55" | ACTIVITY == "I56")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_G46 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "G46")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_G <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "G45" | ACTIVITY == "G46" | ACTIVITY == "G47")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_A <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "A01" | ACTIVITY == "A02" | ACTIVITY == "A03")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_B <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "B05" | ACTIVITY == "B06" | ACTIVITY == "B07"| ACTIVITY == "B08" | ACTIVITY == "B09")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C10" | ACTIVITY == "C11" | ACTIVITY == "C12"| ACTIVITY == "C13" | ACTIVITY == "C14" | ACTIVITY == "C15" | ACTIVITY == "C16" | ACTIVITY == "C17" | ACTIVITY == "C18" | ACTIVITY == "C19" | ACTIVITY == "C20" | ACTIVITY == "C21" | ACTIVITY == "C22" | ACTIVITY == "C23" | ACTIVITY == "C24" | ACTIVITY == "C25" | ACTIVITY == "C26" | ACTIVITY == "C27" | ACTIVITY == "C28" | ACTIVITY == "C29" | ACTIVITY == "C30" | ACTIVITY == "C31" | ACTIVITY == "C32" | ACTIVITY == "C33")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C10T12 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {

  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C10" | ACTIVITY == "C11" | ACTIVITY == "C12")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C13T15 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C13" | ACTIVITY == "C14" | ACTIVITY == "C15")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C16T18 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C16" | ACTIVITY == "C17" | ACTIVITY == "C18")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C19T21 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C19" | ACTIVITY == "C20" | ACTIVITY == "C21")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C19T22 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C19" | ACTIVITY == "C20" | ACTIVITY == "C21" | ACTIVITY == "C22")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C22T23 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C22" | ACTIVITY == "C23")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C24T25 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C24" | ACTIVITY == "C25")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C26T28 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C26" | ACTIVITY == "C27" | ACTIVITY == "C28")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C29T30 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C29" | ACTIVITY == "C30")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C31T33 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C31" | ACTIVITY == "C32" | ACTIVITY == "C33")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_C25T30 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "C25" | ACTIVITY == "C26" | ACTIVITY == "C27" | ACTIVITY == "C28" | ACTIVITY == "C29" | ACTIVITY == "C30")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_D <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "D351" | ACTIVITY == "D352" | ACTIVITY == "D353")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_E <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "E36" | ACTIVITY == "E37" | ACTIVITY == "E38"  | ACTIVITY == "E39")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_E36T37 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "E36" | ACTIVITY == "E37")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_E38T39 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "E38" | ACTIVITY == "E39")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_E37T39 <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "E37" | ACTIVITY == "E38" | ACTIVITY == "E39")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_F <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "F41" | ACTIVITY == "F42" | ACTIVITY == "F43")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_BTE <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "B05" | ACTIVITY == "B06" | ACTIVITY == "B07"| ACTIVITY == "B08" | ACTIVITY == "B09" | ACTIVITY == "C10" | ACTIVITY == "C11" | ACTIVITY == "C12"| ACTIVITY == "C13" | ACTIVITY == "C14" | ACTIVITY == "C15" | ACTIVITY == "C16" | ACTIVITY == "C17" | ACTIVITY == "C18" | ACTIVITY == "C19" | ACTIVITY == "C20" | ACTIVITY == "C21" | ACTIVITY == "C22" | ACTIVITY == "C23" | ACTIVITY == "C24" | ACTIVITY == "C25" | ACTIVITY == "C26" | ACTIVITY == "C27" | ACTIVITY == "C28" | ACTIVITY == "C29" | ACTIVITY == "C30" | ACTIVITY == "C31" | ACTIVITY == "C32" | ACTIVITY == "C33" | ACTIVITY == "D351" | ACTIVITY == "D352" | ACTIVITY == "D353" | ACTIVITY == "E36" | ACTIVITY == "E37" | ACTIVITY == "E38"  | ACTIVITY == "E39")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_GTN <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "G45" | ACTIVITY == "G46" | ACTIVITY == "G47" | ACTIVITY == "H49" | ACTIVITY == "H50" | ACTIVITY == "H51" | ACTIVITY == "H52" | ACTIVITY == "H53" | ACTIVITY == "I55" | ACTIVITY == "I56" | ACTIVITY == "J58" | ACTIVITY == "J59" | ACTIVITY == "J60" | ACTIVITY == "J61" | ACTIVITY == "J62" | ACTIVITY == "J63" | ACTIVITY == "K64" | ACTIVITY == "K65" | ACTIVITY == "K66"| ACTIVITY == "L" | ACTIVITY == "M69" | ACTIVITY == "M70" | ACTIVITY == "M71" | ACTIVITY == "M72" | ACTIVITY == "M73" | ACTIVITY == "M74" | ACTIVITY == "M75" | ACTIVITY == "N77" | ACTIVITY == "N78" | ACTIVITY == "N79" | ACTIVITY == "N80" | ACTIVITY == "N81" | ACTIVITY == "N82")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert_G46TM73_INN <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "G46" | ACTIVITY == "H49" | ACTIVITY == "H50" | ACTIVITY == "H51" | ACTIVITY == "H52" | ACTIVITY == "H53" | ACTIVITY == "J58" | ACTIVITY == "J59" | ACTIVITY == "J60" | ACTIVITY == "J61" | ACTIVITY == "J62" | ACTIVITY == "J63" | ACTIVITY == "K64" | ACTIVITY == "K65" | ACTIVITY == "K66" | ACTIVITY == "M71" | ACTIVITY == "M72" | ACTIVITY == "M73")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}


insert__T <- function(TYPE_ENT_P, ACTIVITY_P, NUMBER_EMPL_P, UNIT_MEASURE_P, INDICATOR_P, CIS_INDICATOR_P, SAVE_FILE_P) {
  
  OBS_VALUE <- Aggregate %>% filter(TYPE_ENT == TYPE_ENT_P & INDICATOR == INDICATOR_P & NUMBER_EMPL == NUMBER_EMPL_P & CIS_INDICATOR == CIS_INDICATOR_P & (ACTIVITY == "B05" | ACTIVITY == "B06" | ACTIVITY == "B07"| ACTIVITY == "B08" | ACTIVITY == "B09" | ACTIVITY == "C10" | ACTIVITY == "C11" | ACTIVITY == "C12"| ACTIVITY == "C13" | ACTIVITY == "C14" | ACTIVITY == "C15" | ACTIVITY == "C16" | ACTIVITY == "C17" | ACTIVITY == "C18" | ACTIVITY == "C19" | ACTIVITY == "C20" | ACTIVITY == "C21" | ACTIVITY == "C22" | ACTIVITY == "C23" | ACTIVITY == "C24" | ACTIVITY == "C25" | ACTIVITY == "C26" | ACTIVITY == "C27" | ACTIVITY == "C28" | ACTIVITY == "C29" | ACTIVITY == "C30" | ACTIVITY == "C31" | ACTIVITY == "C32" | ACTIVITY == "C33" | ACTIVITY == "D351" | ACTIVITY == "D352" | ACTIVITY == "D353" | ACTIVITY == "E36" | ACTIVITY == "E37" | ACTIVITY == "E38"  | ACTIVITY == "E39" | ACTIVITY == "G46" |  ACTIVITY == "H49" | ACTIVITY == "H50" | ACTIVITY == "H51" | ACTIVITY == "H52" | ACTIVITY == "H53" | ACTIVITY == "J58" | ACTIVITY == "J59" | ACTIVITY == "J60" | ACTIVITY == "J61" | ACTIVITY == "J62" | ACTIVITY == "J63" | ACTIVITY == "K64" | ACTIVITY == "K65" | ACTIVITY == "K66" | ACTIVITY == "M71" | ACTIVITY == "M72" | ACTIVITY == "M73")) %>% select(OBS_VALUE)
  OBS_VALUE <- sum(as.numeric(unlist(OBS_VALUE)), na.rm = TRUE)
  Aggregate <<- rbind(Aggregate, list(DATAFLOW, FREQ, TIME_PERIOD, REF_AREA, TABLENAME, ACTIVITY_P, NUMBER_EMPL_P, TYPE_ENT_P, INN_PF, INDICATOR_P, CIS_INDICATOR_P,	OBS_VALUE, UNIT_MEASURE_P, UNIT_MULT, DECIMALS,	OBS_STATUS,	OBS_STATUS_1,	CONF_STATUS, COMMENT_OBS), ignore.attr = TRUE)
  
}